TAP_GITHUB_TOKEN: ENC[AES256_GCM,data:cHPsNlJ9gYtN4UjyoOHq3+msUib82BfdHrD4EEj4gGMUBNrlnRSi10VjO/m6zehBU3d3TWjgs1aiS0YZLeaJGpF35prsvCR6smL7HG/CO9Q2wMY0S0dJmrJ7yrMw,iv:6ytUAPhEgdNLnTeWxe9fqwxbroVxvfs17z0aXkwgWyM=,tag:pBTE/qLBXAzBgh7cjHo56A==,type:str]
PR_DIGEST_PAT: ENC[AES256_GCM,data:uDlUBox/VFL3VkaGZazFcfgWfzzASRUPev+4mQxRfn1XNUBN7eN+Hg==,iv:iAkiLILWczaeu9aRepplHJx3v5Ba8J8ia1vyAN9WvnE=,tag:dhi+E6r88psq4RdIh9W5AQ==,type:str]
SMTP_PASSWORD: ENC[AES256_GCM,data:WeBmnocFN/lIFtx9cnLk5A==,iv:+eJqYVfhuJ3bMr2R0+NWHkMv4/abtuzumGyzcUkTnrc=,tag:Mjkd1oOkEI6FChJLJ4rf9g==,type:str]
SMTP_USERNAME: ENC[AES256_GCM,data:EZo51tcqoD4k,iv:QCnrfnWDBUl9PFR3qOEKokmzisJMkVfxIl+zMUDQ+98=,tag:6iRVtFYHT33P1KpVL672+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eVpLd1BldHpRWDd1eHZV
            dmhNUTk0VzRoSnZLZzZJcFRxM2JWVGJpYVhRCmJXaEswUTh6REZKYU1aUFdOZWlx
            ZDFxbGszQ3RqR2Nsa3VML1BwRFpxZVkKLS0tIEV6SGk1Mm9MbUFwd3RsSXJBRmFC
            R0s5YkludFFwV0FrUlpKbGRva1NncDAKQjEHxmn39VuMSroyQir/fJkVriHtlqrX
            uf/GbwmcOtElr5vrvJ1fwdrrNM0l/3rMpQheLBXVJ2Q3sKfncbCjZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18z4l4rdxmvk394pkpfk6tdnf4q9g0lrl590w6df9ynzqv8n835us7vr5h5
    lastmodified: "2026-09-06T13:52:20Z"
    mac: ENC[AES256_GCM,data:ohGTV6Xdl34IDw1Rshd6+lFAmUIKllMPkW5nKCKprH5sF0mx6aJQpgcJyR18kE60MBj05rCjsW17/JTnC7vrCbNdZKClau/Z5paZqnnpqe1baZ2Nx7EbyZHBKSndHEyVA/mjYcj/SzJi/k0FQgcb2K07OSQ7CYZx1r0JPR+a5y4=,iv:Tsh7ilt4kpAUxkWJBwIx8LF505RpRi2WNgB1vZhasrM=,tag:MRUpAKScidChbfSMiIwuaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
