TAP_GITHUB_TOKEN: ENC[AES256_GCM,data:fLEZ1R3xPnxBVPwgYT1UZ2OCmq0y+ex8ZeYMmtq9GCxmBRLvwEnoQLjvC62wPVg9Q8YxTZYrHt3+vEvE87onVlK/2Zo1drx5bKBjThtWX+uphqy2rlxGUEwsJDHb,iv:DFJrgV9chUdP8z9ccZW1XX7MKnBMpTwPmjdJzNcv97Q=,tag:L+1/MlShYt7HaqOh8kCs8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdVA3WERkNjRSVDVOQUtW
            dGpuM2xvVk5HSGQ2OVMzazJobndVd3FqdmtZCjVBUlVPWjFiQ0tHRXd6bWp2andO
            NUpYV2RVbW9UY25lWEU1R3RpdVVSWFUKLS0tIEJlNHJYQVNyUXZBWDFxZGdXMFFx
            OFhvalJMdC9MeEhidmcvOUJYbEhCR1UK1tuAUMehIPmKV5zC75sP9CRyINDcbCjj
            ODAo/bHQ7ZU/IgEpJhIQdMbOEROTNGHTAvorXUSbO+glbVkaC+Kx5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18z4l4rdxmvk394pkpfk6tdnf4q9g0lrl590w6df9ynzqv8n835us7vr5h5
    lastmodified: "2026-08-23T12:26:31Z"
    mac: ENC[AES256_GCM,data:KGZX8usEldTcJcNgqRIeE0A+iteAx8BT6He4jGtGd5oWECyZyPPpWQYBQxHx8hjqbh+fT86U2qwKCCMII+7MzFgRHCx0kfEYeEeT02dZmDk+KYZDFSNKLLULze0cFVUE8/c8hOTeYuaG98+nejayrrKNwmD1OR2mtNAmaQFI25w=,iv:vCZsnHqRnXDFRM7JBKudXjZLQZlA/9rvjH1PudXTJNc=,tag:86flWgaL7/KCMSEriMpPig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
