name: setup
description: Checkout the repo and set up mise
inputs:
  fetch-depth:
    description: Number of commits to fetch (0 = full history)
    required: false
    default: "1"
runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
        fetch-depth: ${{ inputs.fetch-depth }}
    - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4
