name: digest

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 10 * * 6" # 5am Central (fixed UTC-5 offset; drifts to 4am during CST)
  workflow_dispatch: {}

jobs:
  digest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: hugoh/digest-action@2ba16e00c18ec5261015883e489922e9ad7898bf # v0.3.1
        with:
          owner: hugoh
          github-token: ${{ secrets.PR_DIGEST_PAT }}
          smtp-host: ${{ secrets.SMTP_HOST }}
          smtp-port: ${{ secrets.SMTP_PORT }}
          smtp-username: ${{ secrets.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
          digest-from-email: ${{ secrets.DIGEST_FROM_EMAIL }}
          digest-to-email: ${{ secrets.DIGEST_TO_EMAIL }}
