name: release-asyncgh

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - asyncgh/**
      - .github/workflows/release-asyncgh.yml
      - .github/workflows/release-pypi.yml

jobs:
  publish:
    uses: ./.github/workflows/release-pypi.yml
    permissions:
      id-token: write
    with:
      environment: pypi-asyncgh
      uv-package: asyncgh
