name: release-repokit

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - repokit/**
      - .github/workflows/release-repokit.yml
      - release-pypi/action.yml

jobs:
  publish:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: pypi-repokit
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./release-pypi
        with:
          uv-package: hugoh-repokit
