name: release-asyncgh

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - asyncgh/**
      - .github/workflows/release-asyncgh.yml
      - release-pypi/action.yml

jobs:
  publish:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: pypi-asyncgh
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: ./release-pypi
        with:
          uv-package: asyncgh
