name: release-repokit

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - repokit/**
      - .github/workflows/release-repokit.yml
      - release-pypi/action.yml

jobs:
  publish:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment: pypi-repokit
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: ./release-pypi
        with:
          uv-package: hugoh-repokit
