name: release-reconcilekit

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - reconcilekit/**
      - .github/workflows/release-reconcilekit.yml
      - .github/workflows/release-pypi.yml

jobs:
  publish:
    uses: ./.github/workflows/release-pypi.yml
    permissions:
      id-token: write
    with:
      environment: pypi-reconcilekit
      uv-package: reconcilekit
