name: secret-scan

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "52 7 * * 6"
  workflow_dispatch:
  workflow_call:

permissions: {}

jobs:
  trufflehog:
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number ||
        github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@363923b901c911a9164f50b6c423f47c15372b1c # v3.97.4
        with:
          extra_args: --results=verified
